language: node_js

script: yarn run build

deploy:
  local-dir: dist
  fqdn: masked.radmen.info
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
